import Header from '@/components/Header'
import './globals.css'
import { Manrope } from 'next/font/google'
import { Footer } from '@/components/Footer'
import GoogleAnalytics from '@/components/GoogleAnalytics'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'eJam',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID="G-JZXSKKQZ86" />
      <body className={manrope.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
